server:
    port: 8761
    
spring: 
     application:
            name: service-registery
            
eureka:
     application:
              name: service-registery
              client:
                    register-with-eureka: true
                    fetch-registry: true
                    serviceUrl:
                    defaultZone: http:localhost:8761/eureka/
            
